### Listar categorias
GET http://localhost:5252/api/categorias/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MTU1ODMsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.yQzGHJzrdvoPW40R73rYO8fIVnVsLICroI1gYqKv7so
### Listar custos filtrando por nome
GET http://localhost:5252/api/categorias/listar?nome=comida
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk


### Buscar categoria passando o ID
GET http://localhost:5252/api/categorias/buscar?id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk

### Castrar categoria
POST http://localhost:5252/api/categorias/cadastrar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk

{
  "nome": "Entreterimento"
}

### Editar categoria
PATCH http://localhost:5252/api/categorias/editar?id=14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk

{
  "nome": "Cinema"
}


### Remover categoria
DELETE http://localhost:5252/api/categorias/remover?id=14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk
