### Listar categorias
GET http://localhost:5252/api/categorias/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibXlsZW5hIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibXlsZW5hQGVtYWlsLmNvbSIsImV4cCI6MTc2MDg5NzQzNCwiaXNzIjoiRG90TW9uZXkuQVBJIiwiYXVkIjoiRG90TW9uZXkuQ2xpZW50In0.Bd750LyfULA6-XdQNB6FsRmIuk5v_NKZ1LC4aVGB-c0
### Listar custos filtrando por nome
GET http://localhost:5252/api/categorias/listar?nome=Sapato
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibXlsZW5hIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibXlsZW5hQGVtYWlsLmNvbSIsImV4cCI6MTc2MDg5NzQzNCwiaXNzIjoiRG90TW9uZXkuQVBJIiwiYXVkIjoiRG90TW9uZXkuQ2xpZW50In0.Bd750LyfULA6-XdQNB6FsRmIuk5v_NKZ1LC4aVGB-c0


### Buscar categoria passando o ID
GET http://localhost:5252/api/categorias/buscar?id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibXlsZW5hIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibXlsZW5hQGVtYWlsLmNvbSIsImV4cCI6MTc2MDg5NzQzNCwiaXNzIjoiRG90TW9uZXkuQVBJIiwiYXVkIjoiRG90TW9uZXkuQ2xpZW50In0.Bd750LyfULA6-XdQNB6FsRmIuk5v_NKZ1LC4aVGB-c0

### Castrar categoria
POST http://localhost:5252/api/categorias/cadastrar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibXlsZW5hIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibXlsZW5hQGVtYWlsLmNvbSIsImV4cCI6MTc2MDg5NzQzNCwiaXNzIjoiRG90TW9uZXkuQVBJIiwiYXVkIjoiRG90TW9uZXkuQ2xpZW50In0.Bd750LyfULA6-XdQNB6FsRmIuk5v_NKZ1LC4aVGB-c0

{
  "nome": "Entreterimento"
}

### Editar categoria
PATCH http://localhost:5252/api/categorias/editar?id=6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibXlsZW5hIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibXlsZW5hQGVtYWlsLmNvbSIsImV4cCI6MTc2MDg5NzQzNCwiaXNzIjoiRG90TW9uZXkuQVBJIiwiYXVkIjoiRG90TW9uZXkuQ2xpZW50In0.Bd750LyfULA6-XdQNB6FsRmIuk5v_NKZ1LC4aVGB-c0

{
  "nome": "Cinema"
}


### Remover categoria
DELETE http://localhost:5252/api/categorias/remover?id=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibXlsZW5hIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoibXlsZW5hQGVtYWlsLmNvbSIsImV4cCI6MTc2MDg5NzQzNCwiaXNzIjoiRG90TW9uZXkuQVBJIiwiYXVkIjoiRG90TW9uZXkuQ2xpZW50In0.Bd750LyfULA6-XdQNB6FsRmIuk5v_NKZ1LC4aVGB-c0
