### Listar Custos
GET http://localhost:5252/api/custos/listar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk
### Listar custos filtrando por nome
GET http://localhost:5252/api/custos/listar?descricao=comida
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk


### Buscar custo passando o ID
GET http://localhost:5252/api/custos/buscar?id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk

### Cadastrar custo
POST http://localhost:5252/api/custos/cadastrar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk

{
  "descricao": "Ida no cinema",
  "valor": 120.50,
  "data": "2025-10-18T00:00:00",
  "categoriaId": 7,
  "usuarioId": 1
}

### Editar custo
PATCH http://localhost:5252/api/custos/editar?id=5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk

{
  "descricao": "Ida no cinema",
  "valor": 120.50,
  "data": "2025-10-18T00:00:00",
  "categoriaId": 8,
  "usuarioId": 2
}


### Remover custo
DELETE http://localhost:5252/api/custos/remover?id=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibHVjYXMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJsdWNhc0BlbWFpbC5jb20iLCJleHAiOjE3NjA5MDAyMDUsImlzcyI6IkRvdE1vbmV5LkFQSSIsImF1ZCI6IkRvdE1vbmV5LkNsaWVudCJ9.0zSt3iYCQMHR8v3UY1wGH09L0xRLxVzcgCUt7FfyERk
