### Registrar novo usuário
POST http://localhost:5252/api/auth/register
Content-Type: application/json

{
  "nomeDeUsuario": "muriele",
  "email": "muriele@email.com",
  "senha": "123456"
}

### Fazer login e pegar key JWT
POST http://localhost:5252/api/auth/login
Content-Type: application/json

{
  "nomeDeUsuario": "muriele",
  "senha": "123456"
}