### Listar Custos
GET http://localhost:5252/api/custos/listar

### Listar custos filtrando por nome
GET http://localhost:5252/api/custos/listar?descricao=teste


### Buscar custo passando o ID
GET http://localhost:5252/api/custos/buscar?id=1

### Castrar custo
POST http://localhost:5252/api/custos/cadastrar
Content-Type: application/json

{
  "descricao": "teste",
  "valor": 120.50,
  "data": "2025-10-18T00:00:00",
  "categoriaId": 1,
  "usuarioId": 1
}

### Editar custo
PATCH http://localhost:5252/api/custos/editar?id=1
Content-Type: application/json

{
  "descricao": "Um novo custo",
  "valor": 120.50,
  "data": "2025-10-18T00:00:00",
  "categoriaId": 1,
  "usuarioId": 1
}


### Remover custo
DELETE http://localhost:5252/api/custos/remover?id=2